### ISSUE TITLE
请问table如何才能不导出为图片格式?

### ISSUE THREAD

**Issue by jiangLiu98** [huangbohang/export-word#1]

**Comment by huangbohang** [comment]
那个toImg不要加上对应的table类名即可



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月18日 16:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [huangbohang/export-word] 请问table如何才能不导出为图片格式? (Issue #1) |

**Comment by huangbohang** [comment]
fixed

**Comment by jiangliu3** [comment]
如果toImg为空的话方法会报错，建议修改一下这里的判断条件，或者在demo里面加个备注

**Comment by huangbohang** [comment]
> 如果toImg为空的话方法会报错，建议修改一下这里的判断条件，或者在demo里面加个备注

谢谢你的提议，已修复
